#!/usr/bin/env bash
set -euo pipefail

#
# Clean up passless-boot-tpm state upon successful boot
#

source /usr/lib/passless-boot-tpm_lib.sh

if [ $# -ge 1 ]; then
	luks_slot="$1"
fi
if [ $# -ge 2 ]; then
	service_name="$2"
fi

systemd-cryptenroll --wipe-slot "$luks_slot" "$(cryptroot_device)"

if [ -n "$service_name" ]; then
	systemctl disable "$service_name"
fi

if command -v rguard 2>&1 >/dev/null; then
	if ! rguard -1 --loglevel error; then
		echo "Failed to re-activate reboot-guard"
	fi
fi
